name: Check ESLint

on: [push]
jobs:
  one:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Init node env
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn
      - name: Check ESLint
        run: yarn lint
        env:
          CI: true
