name: Unit test

on: [push]
jobs:
  one:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Init node env
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn
      - name: Unit test
        run: yarn test
        env:
          CI: true
